export const team_images = {
    "América-MG": "https://futebol-120387120312.s3.us-east-2.amazonaws.com/teams/Am%C3%A9rica-MG.png",
    "Atlético-GO": "",
    "Atlético-MG": "",
    "Atlético-PR": "",
    "Avaí": "",
    "Bahia": "",
    "Botafogo": "",
    "Chapecoense": "",
    "Corinthians": "",
    "Coritiba": "",
    "Cruzeiro": "",
    "Flamengo": "",
    "Fluminense": "",
    "Grêmio": "",
    "Internacional": "",
    "Palmeiras": "",
    "Paraná": "",
    "Santos": "",
    "São Paulo": "",
    "Vasco": "",
    "Vitória": "",

}